Fixed navbar oveerflowing
EddieHubCommunity/RepoRater pull request #54
Opened 2023-12-30 07:56 UTC by sohanpaliyal

## Fixes Issue
Closes #41 
Closes #45

## Changes proposed

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2023-12-30 08:02 UTC, yogeshpaliyal commented on src/components/Navbar.js
> +    console.log('handle resixe ===>')
Please remove the console log

2023-12-30 08:02 UTC, yogeshpaliyal commented on src/app/globals.css
> +}
Add a blank line at end

2023-12-30 08:13 UTC, yogeshpaliyal approved these changes

2023-12-30 11:11 UTC, eddiejaoude requested changes
Thank you for the contribution 👍 

We are using tailwind, I think we can use their responsive classes, we don't need all the react code

Documentation https://tailwindcss.com/docs/responsive-design

2023-12-31 07:24 UTC, sohanpaliyal commented
> Thank you for the contribution 👍
> 
> We are using tailwind, I think we can use their responsive classes, we don't need all the react code
> 
> Documentation https://tailwindcss.com/docs/responsive-design

i think we 'll gonna need atleast one useState to handle these classes .except that state i removed all the other unnecessary react code

2023-12-31 20:08 UTC, eddiejaoude commented
I will have a look tomorrow, can you share screenshots please of the changes in desktop and mobile view

2024-01-01 12:31 UTC, sohanpaliyal commented
> I will have a look tomorrow, can you share screenshots please of the changes in desktop and mobile view

![image](https://github.com/EddieHubCommunity/RepoRater/assets/68601638/b4bc21d9-1793-4b32-aad5-578de6353dc7)

![image](https://github.com/EddieHubCommunity/RepoRater/assets/68601638/d0117a6d-1abc-4c79-9a76-d6d4ca5e7094)

![image](https://github.com/EddieHubCommunity/RepoRater/assets/68601638/9be8d17a-9978-4d74-a0d0-24639e8594ea)

2024-01-04 09:49 UTC, eddiejaoude approved these changes
Thank you 👍

2024-01-04 09:50 UTC, eddiejaoude commented
I will merge to a temporary branch and fix the conflicts

2024-01-04 09:51 UTC, eddiejaoude approved these changes

2024-01-04 09:51 UTC, merged